language: php

matrix:
  include:
    - sudo: required
      services:
        - docker
      env:
        - RELEASE=xenial
    - sudo: required
      dist: trusty
      group: edge
      env:
        - RELEASE=trusty
    - sudo: required
      dist: xenial
      group: edge
      env:
        - RELEASE=xenial
  allow_failures:
    - sudo: required
      services:
        - docker
      env:
        - RELEASE=xenial

env:
  global:
  - VERSION=8.1snapshot

install:
- cp $HOME/.php-build/share/php-build/default_configure_options $HOME
- rm -rf $HOME/.phpenv
- git clone 'https://github.com/phpenv/phpenv.git' $HOME/.phpenv
- eval "$($HOME/.phpenv/bin/phpenv init -)"
- pushd $HOME/.php-build
- git checkout master
- git reset --hard origin/master
- git pull
- popd
- mv $HOME/default_configure_options $HOME/.php-build/share/php-build/default_configure_options
- sed -i -e '/xdebug/d' ~/.php-build/share/php-build/definitions/master
- sed -i -e 's/--without-pear/--with-pear/' ~/.php-build/share/php-build/default_configure_options

before_script:
- 'export LSB_RELEASE=${LSB_RELEASE:-$(lsb_release -rs || echo ${$(sw_vers -productVersion)%*.*})}'
- 'export OS_NAME=${OS_NAME:-$(lsb_release -is | tr "A-Z" "a-z" || echo "osx")}'
- 'export ARCH=${ARCH:-$(uname -m)}'
- 'export INSTALL_DEST=${INSTALL_DEST:-$HOME/.phpenv/versions}'
- __dots() { while true ; do echo -en . ; sleep 30 ; done } ; __dots &

script: ./bin/compile

after_success: ./bin/archive

after_failure: cat /tmp/php-build.*.log

addons:
  artifacts:
    paths:
    - $LSB_RELEASE/
    target_paths:
    - /binaries/$OS_NAME/$LSB_RELEASE/$ARCH
